# Generated by Django 5.0.14 on 2026-08-12 07:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('url', models.TextField(help_text='Public S3/R2 CDN URL of the asset')),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False, help_text='Designates primary thumbnail image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='products.product')),
            ],
            options={
                'db_table': 'products_productmedia',
                'ordering': ['display_order', '-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(help_text='Size e.g. S, M, L, XL, XXL, Custom', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Color e.g. Navy Blue, Gold, Black', max_length=50, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('price_override_kobo', models.PositiveBigIntegerField(blank=True, help_text='Optional price override in Kobo if variant price differs from base_price_kobo', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'db_table': 'products_productvariant',
                'ordering': ['size', 'color'],
            },
        ),
    ]
