# Generated by Django 5.0.14 on 2026-09-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.JSONField(blank=True, default=dict, help_text='Temu-style structured sizing and measurement guide data configured by the designer.'),
        ),
    ]
