# Generated by Django 5.0.14 on 2026-08-16 01:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_productmedia_productvariant'),
        ('vendors', '0002_vendorprofile_cac_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('order_status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAID', 'Paid'), ('VENDOR_ACCEPTED', 'Vendor Accepted'), ('PREPARING', 'Preparing'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('PICKED_UP', 'Picked Up'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed')], db_index=True, default='PENDING_PAYMENT', max_length=30)),
                ('subtotal_kobo', models.PositiveBigIntegerField()),
                ('delivery_fee_kobo', models.PositiveBigIntegerField(default=0)),
                ('total_amount_kobo', models.PositiveBigIntegerField()),
                ('payment_expires_at', models.DateTimeField(db_index=True)),
                ('shipping_address_snapshot', models.JSONField(help_text='Immutable JSON snapshot of shipping address at time of order creation')),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title_snapshot', models.CharField(max_length=255)),
                ('variant_size_snapshot', models.CharField(max_length=50)),
                ('variant_color_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('sku_snapshot', models.CharField(max_length=100)),
                ('unit_price_kobo', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('total_price_kobo', models.PositiveBigIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'orders_orderitem',
                'ordering': ['created_at'],
            },
        ),
    ]
