# Generated by Django 5.0.14 on 2026-08-31 06:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_prepared_at_order_ready_for_pickup_at_and_more'),
        ('vendors', '0002_vendorprofile_cac_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_kobo', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PAYOUT_RESERVED', 'Payout Reserved'), ('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed')], default='PAYOUT_RESERVED', max_length=50)),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transfer_code', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='vendors.bankaccount')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Payout Request',
                'verbose_name_plural': 'Payout Requests',
                'db_table': 'payouts_payoutrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_kobo', models.BigIntegerField()),
                ('entry_type', models.CharField(choices=[('EARNING_PENDING', 'Pending Earning'), ('EARNING_RELEASE_TO_AVAILABLE', 'Earning Released to Available'), ('PAYOUT_RESERVE', 'Payout Reserved'), ('PAYOUT_SUCCESS', 'Payout Successful'), ('PAYOUT_FAILED', 'Payout Failed'), ('REFUND', 'Refunded / Cancelled')], max_length=50)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='orders.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='vendors.vendorprofile')),
                ('payout_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payouts.payoutrequest')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'db_table': 'payouts_ledgerentry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pending_balance_kobo', models.PositiveBigIntegerField(default=0)),
                ('available_balance_kobo', models.PositiveBigIntegerField(default=0)),
                ('reserved_balance_kobo', models.PositiveBigIntegerField(default=0)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_balance', to='vendors.vendorprofile')),
            ],
            options={
                'verbose_name': 'Vendor Balance',
                'verbose_name_plural': 'Vendor Balances',
                'db_table': 'payouts_vendorbalance',
            },
        ),
    ]
