# Generated by Django 5.0.14 on 2026-08-16 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('secret_key', models.CharField(max_length=255)),
                ('public_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Provider',
                'verbose_name_plural': 'Payment Providers',
                'db_table': 'payments_paymentprovider',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('PAYSTACK', 'Paystack')], default='PAYSTACK', max_length=20)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True)),
                ('authorization_url', models.URLField(blank=True, max_length=500, null=True)),
                ('amount_kobo', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Requests',
                'db_table': 'payments_paymentrequest',
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=128, unique=True)),
                ('event', models.CharField(choices=[('charge.success', 'Charge Success'), ('charge.failed', 'Charge Failed'), ('charge.reversed', 'Charge Reversed'), ('transfer.initiated', 'Transfer Initiated'), ('transfer.completed', 'Transfer Completed'), ('transfer.failed', 'Transfer Failed')], max_length=30)),
                ('payload', models.JSONField()),
                ('signature_verified', models.BooleanField(default=False)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_webhook_logs', to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment Webhook Log',
                'verbose_name_plural': 'Payment Webhook Logs',
                'db_table': 'payments_paymentwebhooklog',
            },
        ),
    ]
