# Generated by Django 5.0.14 on 2026-08-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentwebhooklog',
            name='reference',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='paymentwebhooklog',
            unique_together={('reference', 'event')},
        ),
    ]
