# Generated by Django 5.0.14 on 2026-08-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='cac_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='kyc_tier',
            field=models.CharField(choices=[('TIER_1_STARTER', 'Tier 1: Starter (Basic Verification)'), ('TIER_2_VERIFIED', 'Tier 2: Verified Designer (ID & NUBAN Verified)'), ('TIER_3_ENTERPRISE', 'Tier 3: Enterprise Partner (Studio Inspected & CAC)')], default='TIER_1_STARTER', max_length=30),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='nin_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='workshop_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
